### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by RyanTG** [RyanTG/pbm#118]
Create /faq

**You should add Johndoeville to your app...?**

We can really only respond to this question with our own questions:

1. Are you willing to serve as the administrator for this new region? It doesn't take much work, but it does require attention to detail and an interest in watching over the data. If the answer is no, we won't add the region. But, be honest about your abilities/willingness to do this.
2. Do you operate pinball machines in the area? The answer to this should be "no."
3. How many locations in your area have machines? The answer to this should be 10 or more. Already having a list of locations to add is a bonus.
4. Are there other people in your area that would help keep the map up to date (such as pinball league members)? This is a user-powered map. It only works when many people are aware of it and updating it. And it's your job to spread the word.

We can't add a new region without the answers to those questions!

**This machine is no longer at this location...?**

This is a user-powered map, and YOU can remove the machine from the location. On the website, just click the "remove" button that's below the machine name. On the app, click on the machine name, and then look for a "remove" button or trash can icon.

**This location closed/no longer has machines... ?**

Simply remove all the machines from it. We get notified once a week about empty locations, and then we delete them (sometimes we wait longer to delete them because we want to verify that the machines are really gone). So, no need to tell us. But still, thanks for telling us and for updating the map!

**Comment by RyanTG** [comment]
@scottwainstock Tell me what you think about this FAQ. I'll try to think of more. Also, it turns out that none of them are actually questions.

**Comment by scottwainstock** [comment]
It looks good to me as is... the only thing that might be handy is more detail on what the responsibilities of an admin are? I don't know.

**Comment by RyanTG** [comment]
Thanks, that's a good idea.

**Comment by RyanTG** [comment]
**What's it take to be a regional administrator?**

As you probably know, this website/app is composed of a lot of separate pinball maps. The intent in keeping them relatively small is that this will make them easier to manage and keep up to date. They cover busy areas where people are actively playing pinball and scouting for machines. So for each map we make, we want at least one local person to serve as that map's administrator.

Regular site visitors can make a lot of map updates, and administrators can make even more! Their most common task is to add new locations. Users submit locations, and admins verify and spellcheck those locations. Admins also:

- Remove empty locations
- Keep an eye on machine comments and machine removals (to make sure people aren't abusing the data)
- Add local pinball links
- Add local events
- Add operators

Admins should *care* about the integrity of the map. They should be careful and consistent with their spelling and punctuation. They should also have an interest in helping spread the word about the map. Each map is for the people who live in that area, and so admins are kind of an ambassador for their local map. They should also be unbiased - each map is a representative of what exists. Any user can leave a comment about a machine or location, so if a place sucks then it will be known. But it's not the admin's role to exclude places because they suck. All locations with publicly playable pinball should be on the map.

**Comment by RyanTG** [comment]
**Why didn't you add the region that I requested?**

Most likely, it's because you didn't answer the above questions.

**Comment by RyanTG** [comment]
https://github.com/RyanTG/pbm/commit/ec371bc0e2c44f0d3af27a3012b425bd63e9c2e5
https://github.com/RyanTG/pbm/commit/4208ec0114a3ed18369c0a53e80ca4614092bb2f
