### ISSUE TITLE
link to profile page when username is displayed.

### ISSUE THREAD

**Issue by RyanTG** [RyanTG/pbm#135]

**Comment by RyanTG** [comment]
@scottwainstock On the website, when a location has "last updated on: date by username" I'd like that "username" to link to the user profile. And I'd like ANY user to see that link. The only code I could find for generating the profile link is:

`(Authorization.current_user && !Authorization.current_user.is_a?(Authorization::AnonymousUser)) ? profile_user_path(Authorization.current_user.id) : inspire_profile_path`

But that only works for the current user. Is there a way for anyone to get a profile path?

**Comment by scottwainstock** [comment]
@RyanTG Should be good... https://github.com/scottwainstock/pbm/commit/8d58fa793b5556fc6c81a6b7cb0feacc67b01457

**Comment by RyanTG** [comment]
Thanks! Looks great. I think this is a nice addition.
